### ISSUE TITLE
Add colorisation in output

### ISSUE THREAD

**Issue by Hofer-Julian** [bilelmoussaoui/flatpak-vscode#33]
See https://github.com/microsoft/vscode-cmake-tools for inspiration

**Comment by bilelmoussaoui** [comment]
I'm tempted to close this, because vscode itself doesn't allow you to color outputs; see https://github.com/Microsoft/vscode/issues/571

The only way you can do this is by adding a `x-code-output` "mimetype" support, see https://github.com/IBM-Cloud/vscode-log-output-colorizer/blob/master/package.json#L28  which is very limited and doesn't allow you to use any ANSI characters so you can't really color things as you receive from say flatpak/meson whatever.

For anyone interested in a very limited syntax coloring, please install this extension https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer.

**Comment by Hofer-Julian** [comment]
Sure
