### ISSUE TITLE
Disable building when there are some errors in the manifest

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#78]
Related with #1

There could also be message about the missing runtime on the #71's active manifest status bar item.

**Comment by bilelmoussaoui** [comment]
The same would be needed for sdk extensions. So we probably need some way to get that information at first run and re-check later on somehow because the user might install those. The biggest issue with SDK extensions is we will need to resolve the version that should be installed; so rust-stable sdk extension with the GNOME Sdk 41, should map to fdo 21.08 and so to rust-stable//21.08 instead of rust-stable//41 which doesn't exists.

Once we can do all of this and we have that information, we could easily implement something to allow the user installing them like mentioned on #1 on top of that
