### ISSUE TITLE
Use json schema to detect manifests

### ISSUE THREAD

**Issue by Hofer-Julian** [bilelmoussaoui/flatpak-vscode#9]
Maybe https://www.npmjs.com/package/jsonschema can be used for that

**Comment by tristan957** [comment]
I think this issue might be related to what I am experiencing.

```
Property proseWrap is not allowed.yaml-schema: file:///home/tristan957/.vscode/extensions/bilelmoussaoui.flatpak-vscode-0.0.5/manifest-schema.json
```

Seeing that on my .prettierrc.yaml file.

**Comment by tristan957** [comment]
Which if I understand you Julian is because the extension thinks any yaml file is a Flatapk schema?

**Comment by Hofer-Julian** [comment]
That is incorrelated @tristan957
Mine is a feature request, yours should be bug report :)

**Comment by bilelmoussaoui** [comment]
I believe this is no longer needed because we enforce that the manifest has a valid app-id on it name, that reduces the number of potentially wrong selections of the manifest. Along with #8 once fixed, such checks will no longer be required. Especially that the upstream schema might be incomplete and could cause us to fail selecting that manifest
